// Generated by Wrangler
// After adding bindings to `wrangler.json`, regenerate this interface via `npm run cf-typegen`
interface Env {
  TELEGRAM_BOT_TOKEN: any;
  CHANNEL_CHAT_ID: any;
  LINK_SUBSCRIBED_CHANNEL: any;
  BOT_TOKEN: any;
}
