
name = "tgbotmepinstorelike"
main = "src/index.ts"
compatibility_date = "2025-01-24"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
TELEGRAM_BOT_TOKEN = "7749452761:AAFa5bRidAx8_UlbKIPVbEqxHk3dXozu6Ks"
CHANNEL_CHAT_ID = "-1002345480384"
LINK_SUBSCRIBED_CHANNEL = "https://t.me/+LRi3iRUdIA5lYThi"
